# Generated by Django 5.0.1 on 2024-02-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='student/', verbose_name='image')),
            ],
        ),
    ]
