# Generated by Django 5.0.1 on 2024-02-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_category_cities_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirWays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cities',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='city/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='cities',
            name='air',
            field=models.ManyToManyField(blank=True, null=True, related_name='city', to='student.airways'),
        ),
    ]
